spring.application.name=nemo
server.port=8081

# Bypass Incompatible Class Format
spring.classformat.ignore=true

# Koneksi Database (Port 3309 sesuai Workbench kamu)
spring.datasource.url=jdbc:mysql://localhost:3309/mahasiswa_db?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=Ajo010505
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect